import Navbar from '@/components/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-[#262626] text-[#f5f5f5]">
        <div className='flex flex-row h-full'>
          <Navbar />
          <div className='ml-[298px] w-full min-h-screen'>
          {children}
          </div>
        </div> 
      </body>
    </html>
  )
}
